package template

import (
	"fmt"
	"strings"
	"text/template"
)

func Generate(arguments, pkg, prefix string, content *[]byte) (*[]byte, error) {
	contentArr := []string{"``"}
	contentStr := string(*content)
	for {
		if len(contentStr) < 72 {
			contentArr = append(contentArr, "  `"+string(contentStr)+"`")
			break
		}
		contentArr = append(contentArr, "  `"+string(contentStr[:72])+"`")
		contentStr = contentStr[72:]
	}
	tmplData := struct {
		Arguments string
		Pkg       string
		Prefix    string
		Content   []string
		Raw       string
	}{
		Arguments: arguments,
		Pkg:       pkg,
		Prefix:    prefix,
		Content:   contentArr,
		Raw:       "`",
	}

	tmpl, err := template.New("").Parse(
		`// Code generated by "file2go {{.Arguments}}"; DO NOT EDIT.

package {{.Pkg}}

import (
  "time"

  "github.com/pscn/file2go/decode"
)

const content{{.Prefix}} = {{range $i,$c := .Content}}{{$c}} +
{{ end }}  {{.Raw}}{{.Raw}}

var file{{.Prefix}} *decode.File

func init() {
  var err error
  file{{.Prefix}}, err = decode.Init(content{{.Prefix}})
  if err != nil {
  	panic(err)
  }
}

func {{.Prefix}}Content() *[]byte    { return file{{.Prefix}}.Content() }
func {{.Prefix}}Name() *string       { return file{{.Prefix}}.Name() }
func {{.Prefix}}Comment() *string    { return file{{.Prefix}}.Comment() }
func {{.Prefix}}ModTime() *time.Time { return file{{.Prefix}}.ModTime() }

// eof
`)
	if err != nil {
		return nil, fmt.Errorf("failed to parse internal template: error=%s", err)
	}
	var b strings.Builder
	err = tmpl.Execute(&b, tmplData)
	if err != nil {
		return nil, fmt.Errorf("failed to execute template: error=%s", err)
	}
	result := []byte(b.String())
	return &result, nil
}
